### ISSUE TITLE
Marathon task launch timeout.

### ISSUE THREAD

**Issue by IshwarKanse** [AnsibleShipyard/ansible-marathon#10]
Where do I specify the --task_launch_timeout variable for Marathon. We have a slow internet connection thus it takes time to pull the docker images. I have increased the executor_registration_timeout for all  the mesos slaves, which I found in https://github.com/AnsibleShipyard/ansible-mesos/blob/master/vars/main.yml but we need to also increase the task_launch_timeout for Marathon.

**Comment by jolexa** [comment]
You could set a value in /etc/marathon/conf/task_launch_timeout
