### ISSUE TITLE
Support JAVA_OPTS ?

### ISSUE THREAD

**Issue by jolexa** [AnsibleShipyard/ansible-marathon#15]
It would be nice to have a place to set JAVA_OPTS

https://mesosphere.github.io/marathon/docs/command-line-flags.html

For now, I'm adding it to my environment but that doesn't seem very safe overall.

**Comment by ninthnails** [comment]
@jolexa, enhancement coming with PR #19.

**Comment by JasonGiedymin** [comment]
Merged!
