### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by JasonGiedymin** [AnsibleShipyard/ansible-marathon#25]
Add gitter link: https://gitter.im/AnsibleShipyard/devs?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by JasonGiedymin** [comment]
Just needs a badge in the `readme.md`.

[![Gitter](https://badges.gitter.im/gitterHQ/gitter.svg)](https://gitter.im/AnsibleShipyard/devs)

```markdown
[![Gitter](https://badges.gitter.im/gitterHQ/gitter.svg)](https://gitter.im/AnsibleShipyard/devs)
```

**Comment by ernestas-poskus** [comment]
:+1:

**Comment by ernestas-poskus** [comment]
Done.
